<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <title>Welcome To Customer Statisfaction Survey <?php echo date('Y') ?></title>
        <!-- Favicon-->
        <link rel="icon" href="favicon.ico" type="image/x-icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

        <!-- Bootstrap Core Css -->
        <link href="css/bootstrap.css" rel="stylesheet">

        <!-- Waves Effect Css -->
        <link href="css/waves.css" rel="stylesheet" />

        <!-- Animation Css -->
        <link href="css/animate.css" rel="stylesheet" />

        <!-- Morris Chart Css-->
        <link href="css/morris.css" rel="stylesheet" />

        <!-- Custom Css -->
        <link href="css/style.css" rel="stylesheet">

        <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
        <link href="css/themes/all-themes.css" rel="stylesheet" />	


        <!-- Jquery Core Js -->
        <script src="js/jquery-1.10.2.js"></script>
        <script src="js/jquery.form.js"></script>

        <!-- Bootstrap Core Js -->
        <script src="js/bootstrap.js"></script>

        <!-- Select Plugin Js -->
        <script src="js/bootstrap-select.js"></script>

        <!-- Slimscroll Plugin Js -->
        <script src="js/jquery.slimscroll.js"></script>

        <!-- Waves Effect Plugin Js -->
        <script src="js/waves.js"></script>

        <!-- Jquery CountTo Plugin Js -->
        <script src="js/jquery.countTo.js"></script>

        <!-- Morris Plugin Js -->
        <script src="js/raphael.js"></script>
        <script src="js/morris.js"></script>

        <!-- ChartJs -->
        <script src="js/Chart.bundle.js"></script>

        <!-- Custom Js -->
        <script src="js/admin.js"></script>

        <!-- Input Mask Plugin Js -->
        <script src="js/jquery.inputmask.bundle.js"></script>

        <!-- TinyMCE -->
        <script src="tinymce/tinymce.js"></script>


    </head>